/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileUsernameRouteImport } from './routes/profile/$username'
import { Route as ItinerariesIdRouteImport } from './routes/itineraries/$id'
import { Route as ActivitiesCityRouteImport } from './routes/activities/$city'
import { Route as ProtectedMyItinerariesRouteImport } from './routes/_protected/my-itineraries'
import { Route as ProtectedMyActivitiesRouteImport } from './routes/_protected/my-activities'
import { Route as ItinerariesCitiesCityIdRouteImport } from './routes/itineraries/cities.$cityId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ItinerariesIdRoute = ItinerariesIdRouteImport.update({
  id: '/itineraries/$id',
  path: '/itineraries/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesCityRoute = ActivitiesCityRouteImport.update({
  id: '/activities/$city',
  path: '/activities/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedMyItinerariesRoute = ProtectedMyItinerariesRouteImport.update({
  id: '/my-itineraries',
  path: '/my-itineraries',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMyActivitiesRoute = ProtectedMyActivitiesRouteImport.update({
  id: '/my-activities',
  path: '/my-activities',
  getParentRoute: () => ProtectedRoute,
} as any)
const ItinerariesCitiesCityIdRoute = ItinerariesCitiesCityIdRouteImport.update({
  id: '/itineraries/cities/$cityId',
  path: '/itineraries/cities/$cityId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/my-activities': typeof ProtectedMyActivitiesRoute
  '/my-itineraries': typeof ProtectedMyItinerariesRoute
  '/activities/$city': typeof ActivitiesCityRoute
  '/itineraries/$id': typeof ItinerariesIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/itineraries/cities/$cityId': typeof ItinerariesCitiesCityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/my-activities': typeof ProtectedMyActivitiesRoute
  '/my-itineraries': typeof ProtectedMyItinerariesRoute
  '/activities/$city': typeof ActivitiesCityRoute
  '/itineraries/$id': typeof ItinerariesIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/itineraries/cities/$cityId': typeof ItinerariesCitiesCityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/community': typeof CommunityRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_protected/my-activities': typeof ProtectedMyActivitiesRoute
  '/_protected/my-itineraries': typeof ProtectedMyItinerariesRoute
  '/activities/$city': typeof ActivitiesCityRoute
  '/itineraries/$id': typeof ItinerariesIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/itineraries/cities/$cityId': typeof ItinerariesCitiesCityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community'
    | '/login'
    | '/signup'
    | '/my-activities'
    | '/my-itineraries'
    | '/activities/$city'
    | '/itineraries/$id'
    | '/profile/$username'
    | '/api/auth/$'
    | '/itineraries/cities/$cityId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/login'
    | '/signup'
    | '/my-activities'
    | '/my-itineraries'
    | '/activities/$city'
    | '/itineraries/$id'
    | '/profile/$username'
    | '/api/auth/$'
    | '/itineraries/cities/$cityId'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/community'
    | '/login'
    | '/signup'
    | '/_protected/my-activities'
    | '/_protected/my-itineraries'
    | '/activities/$city'
    | '/itineraries/$id'
    | '/profile/$username'
    | '/api/auth/$'
    | '/itineraries/cities/$cityId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  CommunityRoute: typeof CommunityRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ActivitiesCityRoute: typeof ActivitiesCityRoute
  ItinerariesIdRoute: typeof ItinerariesIdRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ItinerariesCitiesCityIdRoute: typeof ItinerariesCitiesCityIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itineraries/$id': {
      id: '/itineraries/$id'
      path: '/itineraries/$id'
      fullPath: '/itineraries/$id'
      preLoaderRoute: typeof ItinerariesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/$city': {
      id: '/activities/$city'
      path: '/activities/$city'
      fullPath: '/activities/$city'
      preLoaderRoute: typeof ActivitiesCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/my-itineraries': {
      id: '/_protected/my-itineraries'
      path: '/my-itineraries'
      fullPath: '/my-itineraries'
      preLoaderRoute: typeof ProtectedMyItinerariesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/my-activities': {
      id: '/_protected/my-activities'
      path: '/my-activities'
      fullPath: '/my-activities'
      preLoaderRoute: typeof ProtectedMyActivitiesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/itineraries/cities/$cityId': {
      id: '/itineraries/cities/$cityId'
      path: '/itineraries/cities/$cityId'
      fullPath: '/itineraries/cities/$cityId'
      preLoaderRoute: typeof ItinerariesCitiesCityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedMyActivitiesRoute: typeof ProtectedMyActivitiesRoute
  ProtectedMyItinerariesRoute: typeof ProtectedMyItinerariesRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedMyActivitiesRoute: ProtectedMyActivitiesRoute,
  ProtectedMyItinerariesRoute: ProtectedMyItinerariesRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  CommunityRoute: CommunityRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ActivitiesCityRoute: ActivitiesCityRoute,
  ItinerariesIdRoute: ItinerariesIdRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ItinerariesCitiesCityIdRoute: ItinerariesCitiesCityIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
