/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ItinerariesIdRouteImport } from './routes/itineraries/$id'
import { Route as ActivitiesCityRouteImport } from './routes/activities/$city'
import { Route as ItinerariesCitiesCityIdRouteImport } from './routes/itineraries/cities.$cityId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItinerariesIdRoute = ItinerariesIdRouteImport.update({
  id: '/itineraries/$id',
  path: '/itineraries/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesCityRoute = ActivitiesCityRouteImport.update({
  id: '/activities/$city',
  path: '/activities/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const ItinerariesCitiesCityIdRoute = ItinerariesCitiesCityIdRouteImport.update({
  id: '/itineraries/cities/$cityId',
  path: '/itineraries/cities/$cityId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/activities/$city': typeof ActivitiesCityRoute
  '/itineraries/$id': typeof ItinerariesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/itineraries/cities/$cityId': typeof ItinerariesCitiesCityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/activities/$city': typeof ActivitiesCityRoute
  '/itineraries/$id': typeof ItinerariesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/itineraries/cities/$cityId': typeof ItinerariesCitiesCityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/activities/$city': typeof ActivitiesCityRoute
  '/itineraries/$id': typeof ItinerariesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/itineraries/cities/$cityId': typeof ItinerariesCitiesCityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community'
    | '/login'
    | '/signup'
    | '/activities/$city'
    | '/itineraries/$id'
    | '/api/auth/$'
    | '/itineraries/cities/$cityId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/login'
    | '/signup'
    | '/activities/$city'
    | '/itineraries/$id'
    | '/api/auth/$'
    | '/itineraries/cities/$cityId'
  id:
    | '__root__'
    | '/'
    | '/community'
    | '/login'
    | '/signup'
    | '/activities/$city'
    | '/itineraries/$id'
    | '/api/auth/$'
    | '/itineraries/cities/$cityId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityRoute: typeof CommunityRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ActivitiesCityRoute: typeof ActivitiesCityRoute
  ItinerariesIdRoute: typeof ItinerariesIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ItinerariesCitiesCityIdRoute: typeof ItinerariesCitiesCityIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itineraries/$id': {
      id: '/itineraries/$id'
      path: '/itineraries/$id'
      fullPath: '/itineraries/$id'
      preLoaderRoute: typeof ItinerariesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/$city': {
      id: '/activities/$city'
      path: '/activities/$city'
      fullPath: '/activities/$city'
      preLoaderRoute: typeof ActivitiesCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itineraries/cities/$cityId': {
      id: '/itineraries/cities/$cityId'
      path: '/itineraries/cities/$cityId'
      fullPath: '/itineraries/cities/$cityId'
      preLoaderRoute: typeof ItinerariesCitiesCityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityRoute: CommunityRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ActivitiesCityRoute: ActivitiesCityRoute,
  ItinerariesIdRoute: ItinerariesIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ItinerariesCitiesCityIdRoute: ItinerariesCitiesCityIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
